### ISSUE TITLE
Help with translating

### ISSUE THREAD

**Issue by liomore** [Ec-25/FixIt#1]
Hi 👋
I would like to help translate this tool in French. Would you be interested? If so, let me know!
Thanks for this amazing tool btw!
Nathan

**Comment by Ec-25** [comment]
Hello Nathan, thank you very much for your comment.
I am working on an update with some changes and will add a site for translations where they would already be available in English and Spanish.
I would appreciate your help with the French translation, that would be great.

**Comment by pro11x11** [comment]
i can also translate in french
Would you be interested?

**Comment by Ec-25** [comment]
of course @pro11x11  , all contributions that help the tool grow are welcome.
